apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  MONGO_URI: {{ .Values.secret.MONGO_URI | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}